name: "exp108 lr=5e-4"
exp: exp188
seed: 77

title_tfidf_n_components: 50
title_tfidf_reducer: PCA

cv_config:
  name: GroupKFold
  target: label_group
  n_splits: 5

train_config:
  resume_from_exp: exp188
  train_batch_size: 16
  valid_batch_size: 32
  epochs: 10
  num_workers: 2

inference_config:
  threshold: 60
  model_checkpoints:
    - exp108_-1_efficientnet_b3_epoch=09.ckpt
    - exp017_-1_cahya_distilbert-base-indonesian_epoch=09.ckpt
    - exp055_-1_distilbert-base-uncased_epoch=09.ckpt
  thresholds:
    - 60
    - 85
  epoch_configs:
    - dataloader_exp: exp017
      model_checkpoints:
        - exp108_-1_efficientnet_b3_epoch=09.ckpt
        - exp017_-1_cahya_distilbert-base-indonesian_epoch=09.ckpt
    - dataloader_exp: exp055
      model_checkpoints:
        - exp055_-1_distilbert-base-uncased_epoch=09.ckpt
    # - dataloader_exp: exp055
    #   model_checkpoints:
    #     - exp055_-1_distilbert-base-uncased_epoch=09.ckpt
  with_tfidf: False
  tfidf_threshold: 85
  tfidf_max_features: 10000
  ensemble_method: concat
  weights:
    - 50
    # - 60
    - 50
  concat_configs:
    - weights:
        - 50
      idxs:
        - 0
    - weights:
        - 50
        - 50
      idxs:
        - 1
        - 2


dataset_config:
  img_size: 680

model_config:
  model_name: ShopeeImgNet2
  model_arch: efficientnet_b3
  pretrained: True
  channel_size: 2048
  dropout: 0.0
  bert_model_arch: cahya/distilbert-base-indonesian

optimizer_config:
  name: Adam
  params:
    lr: 0.0005

scheduler_config:
  name: ReduceLROnPlateau
  params:
    patience: 0
    factor: 0.1
    mode: max

met_config:
  name: ArcMarginProduct
  params:
    s: 50.0
    m: 0.5
    easy_margin: False
    smoothing: 0.0

transform_config:
  train:
    - name: Resize
      args:
        height: 680
        width: 680
    - name: HorizontalFlip
      args:
        p: 0.5
    - name: ShiftScaleRotate
      args:
        p: 0.5
    - name: HueSaturationValue
      args:
        hue_shift_limit: 0.2
        sat_shift_limit: 0.2
        val_shift_limit: 0.2
        p: 0.5
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
    - name: CoarseDropout
      args:
        p: 0.5

  valid:
    - name: Resize
      args:
        height: 680
        width: 680
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0

  inference:
    - name: Resize
      args:
        height: 680
        width: 680
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
