name: "bert-base-multilingual-uncased hs-mean"
exp: exp198
seed: 77

title_tfidf_n_components: 50
title_tfidf_reducer: PCA

cv_config:
  name: GroupKFold
  target: label_group
  n_splits: 5

train_config:
  resume_from_exp: exp198
  train_batch_size: 16
  valid_batch_size: 32
  epochs: 10
  num_workers: 2

inference_config:
  threshold: 60
  model_checkpoints:
    - exp198_-1_bert-base-multilingual-uncased_epoch=09.ckpt
  thresholds:
    - 55
    - 80
    - 80
  epoch_configs:
    - dataloader_exp: exp204
      model_checkpoints:
        - exp204_0_bert-base-uncased_epoch=06_threshold=45.0_valid_f1=0.8059.ckpt
        - exp198_-1_bert-base-multilingual-uncased_epoch=11.ckpt
        - exp195_-1_cahya_distilbert-base-indonesian_epoch=11.ckpt
        - exp204_0_bert-base-uncased_epoch=06_threshold=45.0_valid_f1=0.8059.ckpt
        - exp196_0_cahya_bert-base-indonesian-522M_epoch=09_threshold=45.0_valid_f1=0.8092.ckpt
  concat_configs:
    - weights:
        - 50
      idxs:
        - 0
  with_tfidf: False
  tfidf_threshold: 85
  tfidf_max_features: 10000
  ensemble_method: concat_voting
  weights:
    - 50
    # - 60
    - 50

dataset_config:
  img_size: 512
  text_col: title
  padding: True
  truncation: True
  max_length: 128

model_config:
  model_name: ShopeeTextNet
  model_arch: efficientnet_b3
  pretrained: True
  channel_size: 768
  dropout: 0.5
  bert_model_arch: bert-base-multilingual-uncased
  bert_hidden_size: 768
  stage1_checkpoint: None

bert_pooling_config:
  name: hs-mean
  params:
    hs_idxs:
      - -1
      - -2
      - -3
      - -4

optimizer_config:
  name: Adam
  params:
    lr: 0.00005

scheduler_config:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 1
    eta_min: 0.000001
    last_epoch: -1

met_config:
  name: ArcMarginProduct
  params:
    s: 50.0
    m: 0.5
    easy_margin: False
    smoothing: 0.0

transform_config:
  train:
    - name: Resize
      args:
        height: 512
        width: 512
    - name: HorizontalFlip
      args:
        p: 0.5
    - name: ShiftScaleRotate
      args:
        p: 0.5
    - name: HueSaturationValue
      args:
        hue_shift_limit: 0.2
        sat_shift_limit: 0.2
        val_shift_limit: 0.2
        p: 0.5
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
    - name: CoarseDropout
      args:
        p: 0.5

  valid:
    - name: Resize
      args:
        height: 860
        width: 860
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0

  inference:
    - name: Resize
      args:
        height: 860
        width: 860
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
