name: "vit_384 IN2 d=0"
exp: exp103
seed: 77

title_tfidf_n_components: 50
title_tfidf_reducer: PCA

cv_config:
  name: GroupKFold
  target: label_group
  n_splits: 5

train_config:
  resume_from_exp: exp103
  train_batch_size: 16
  valid_batch_size: 32
  epochs: 10
  num_workers: 2

inference_config:
  threshold: 60
  model_checkpoints:
    - exp011_-1_efficientnet_b3_epoch=09.ckpt
    # - exp011_0_efficientnet_b3_epoch=09_threshold=40.0_valid_f1=0.8009.ckpt
    # - exp011_1_efficientnet_b3_epoch=06_threshold=40.0_valid_f1=0.8080.ckpt
    # - exp011_2_efficientnet_b3_epoch=06_threshold=40.0_valid_f1=0.8096.ckpt
  thresholds:
    - 60

dataset_config:
  img_size: 384

model_config:
  model_name: ShopeeImgNet2
  model_arch: vit_base_patch16_384
  pretrained: True
  channel_size: 512
  dropout: 0.0
  # bert_model_arch: cahya/distilbert-base-indonesian
  bert_model_arch: distilbert-base-uncased

optimizer_config:
  name: Adam
  params:
    lr: 0.0001
    weight_decay: 0.000001

scheduler_config:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 10
    T_mult: 1
    eta_min: 0.000001
    last_epoch: -1

met_config:
  name: ArcMarginProduct
  params:
    s: 50.0
    m: 0.5
    easy_margin: False
    smoothing: 0.0

transform_config:
  train:
    - name: Resize
      args:
        height: 384
        width: 384
    - name: HorizontalFlip
      args:
        p: 0.5
    - name: ShiftScaleRotate
      args:
        p: 0.5
    - name: HueSaturationValue
      args:
        hue_shift_limit: 0.2
        sat_shift_limit: 0.2
        val_shift_limit: 0.2
        p: 0.5
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
    - name: CoarseDropout
      args:
        p: 0.5

  valid:
    - name: Resize
      args:
        height: 384
        width: 384
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0

  inference:
    - name: Resize
      args:
        height: 384
        width: 384
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
