name: "exp309 with pre-train is=640 cs=1024"
exp: exp311
seed: 77

title_tfidf_n_components: 50
title_tfidf_reducer: PCA

cv_config:
  name: GroupKFold
  target: label_group
  n_splits: 5
  fold_col: kurupical_fold

train_config:
  resume_from_exp: exp311
  train_batch_size: 16
  valid_batch_size: 32
  epochs: 10
  num_workers: 2

inference_config:
  threshold: 60
  model_checkpoints: []
  thresholds:
    - 65
  epoch_configs:
    - dataloader_exp: exp200
      model_checkpoints:
        - exp200_-1_epoch09.ckpt
    - dataloader_exp: exp205
      model_checkpoints:
        - exp205_-1_epoch09.ckpt
    - dataloader_exp: exp207
      model_checkpoints:
        - exp207_-1_epoch09.ckpt
  concat_configs:
    - weights:
        - 50
        - 50
        - 50
      idxs:
        - 0
        - 1
        - 2
      min_indices: 2
  with_tfidf: False
  tfidf_threshold: 85
  tfidf_max_features: 10000
  ensemble_method: concat_voting
  weights: []


dataset_config:
  img_size: 640

model_config:
  model_name: ShopeeImgTextNet3
  model_arch: efficientnet_b3
  pretrained: True
  channel_size: 1024
  dropout: 0.5
  dropout_nlp: 0.5
  dropout_bert_stack: 0.2
  bert_model_arch: cahya/distilbert-base-indonesian
  img_checkpoint: exp300
  txt_checkpoint: exp301

bert_pooling_config:
  name: hs-mean
  params:
    hs_idxs:
      - -1
      - -2
      - -3
      - -4

optimizer_config:
  name: Adam
  params:
    lr: 0.0003
    bert_lr: 0.00001
    fc_lr: 0.0005

scheduler_config:
  name: ReduceLROnPlateau
  params:
    patience: 0
    factor: 0.1
    mode: max

met_config:
  name: ArcMarginProduct
  params:
    s: 32.0
    m: 0.5
    easy_margin: False
    smoothing: 0.0

transform_config:
  train:
    - name: Resize
      args:
        height: 640
        width: 640
    - name: HorizontalFlip
      args:
        p: 0.5
    - name: ImageCompression
      args:
        quality_lower: 99
        quality_upper: 100
    - name: ShiftScaleRotate
      args:
        shift_limit: 0.2
        scale_limit: 0.2
        rotate_limit: 10
        border_mode: 0
        p: 0.7
    - name: Resize
      args:
        height: 640
        width: 640
    - name: Cutout
      args:
        max_h_size: 205
        max_w_size: 205
        num_holes: 1
        p: 0.5
    - name: Normalize
      args: {}

  valid:
    - name: Resize
      args:
        height: 640
        width: 640
    - name: Normalize
      args: {}

  inference:
    - name: Resize
      args:
        height: 640
        width: 640
    - name: Normalize
      args:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        max_pixel_value:
          - 255.0
        p: 1.0
